# Generated by Django 6.1 on 2026-08-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
