# Generated by Django 6.1 on 2026-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(default="Booked", max_length=50)),
                ("payment_status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("rating", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_status", models.CharField(default="Paid", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
