# Generated by Django 6.1 on 2026-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_appointment_combo_feedback_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15,
                blank=True,
                null=True
            ),
        ),
    ]