# Generated by Django 6.1 on 2026-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
